appstor/accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
 
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login')
]

appstor/apps/urls.py
from django.urls import path
from .views import AppDetail, category,home,searchposts

app_name = "apps"
urlpatterns = [
    path('', home, name = "home"),
    path('app/<slug:slug>', AppDetail, name = "app_detail"),
    path('category/<slug:slug>', category, name = "category"),
    path('search/', searchposts, name = "searchposts"),
]

appstor/appstor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include
from accounts.views import signup_view , login_view



urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include("apps.urls")),
    path('', include("apps.urls", namespace='search')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    #path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appstor/accounts/models.py
from django.db import models

# Create your models here.

appstor/apps/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import random


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.title


#class Property(models.Model):
#    title = models.CharField(max_length=200)
#    value = models.CharField(max_length=400)
#    def __str__(self):
#        return self.title + " : " + self.value

class App(models.Model):
    title=models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    category = models.ManyToManyField(Category, related_name="apps")
    price = models.IntegerField()
 #   pr = models.ManyToManyField(Property, related_name="apps")
    thumbnail = models.ImageField(upload_to="images")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description=models.TextField()
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(App, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


    #def __str__(self):
    #    return self.user.username

appstor/apps/forms.py
from django import forms 
from .models import Comment 
  
class CommentForm(forms.ModelForm): 
    content = forms.CharField(label ="", widget = forms.Textarea( 
    attrs ={ 
        'class':'form-control', 
        'placeholder':'Comment here !', 
        'rows':4, 
        'cols':50
    })) 
    class Meta: 
        model = Comment 
        fields =['content']

appstor/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
 
 
# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login')
            #return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
            #return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

appstor/apps/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import CommentForm 
from django.shortcuts import redirect

from django.db.models import Q

def home(request):
    context = {
        #"apps": App.objects.filter(status = 'n').order_by('-created'),
        "apps": App.objects.order_by('-created'),
    }
    return render(request, "apps/index.html", context)

def AppDetail(request, slug):
    if request.method == 'POST': 
        cf = CommentForm(request.POST or None) 
        if cf.is_valid(): 
            content = request.POST.get('content') 
            post=get_object_or_404(App, slug = slug)
            comment = Comment.objects.create(post = post, user = request.user, content = content) 
            comment.save() 
            #return redirect("/") 
    else: 
      cf = CommentForm() 
        
    context = {
        "app": get_object_or_404(App, slug = slug),
        'comment_form':cf,
    }
    return render(request, "apps/app_detail.html", context)

def category(request, slug):
    context = {
        "category": get_object_or_404(Category, slug = slug),
    }
    return render(request, "apps/category.html", context)


def searchposts(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(title__icontains=query) 

            results= App.objects.filter(lookups).distinct()

            context={'results': results,
                     'submitbutton': submitbutton}

            return render(request, 'apps/search_app.html', context)

        else:
            return render(request, 'apps/search_app.html')

    else:
        return render(request, 'apps/search_app.html')

appstor/accounts/templates/accounts/layout/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="../accounts.css">
    <link rel="stylesheet" href="../login.css">
    <title>Appstore</title>
</head>
<body >
{% block content %}

{% endblock content %}
</body>
</html>

appstor/accounts/templates/accounts/login.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
<style>
    html {
        height: 100%;
    }

    body {
        margin: 0;
        padding: 0;
        font-family: sans-serif;
        background: linear-gradient(#141e30, #243b55);
    }
    form{
        display: flex;
        flex-direction: column;
    }
    .login-box {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 400px;
        padding: 40px;
        transform: translate(-50%, -50%);
        background: rgba(0, 0, 0, .5);
        box-sizing: border-box;
        box-shadow: 0 15px 25px rgba(0, 0, 0, .6);
        border-radius: 10px;
    }

    .login-box h2 {
        margin: 0 0 30px;
        padding: 0;
        color: #fff;
        text-align: center;
    }

    .login-box form {
        position: relative;
    }

    .login-box form input {
        width: 100%;
        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        margin-bottom: 30px;
        border: none;
        border-bottom: 1px solid #fff;
        outline: none;
        background:   inherit;;
    }

    .login-box form label {

        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        pointer-events: none;
        transition: .5s;
    }



    .login-box form .submit {
        position: relative;
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 16px;
        text-decoration: none;
        text-transform: uppercase;
        overflow: hidden;
        transition: .5s;
        margin-top: 40px;
        letter-spacing: 4px
    }

    .login-box .submit:hover {
        background: #03e9f4;
        color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 5px #03e9f4,
        0 0 25px #03e9f4,
        0 0 50px #03e9f4,
        0 0 100px #03e9f4;
    }

    .login-box .submit span {
        position: absolute;
        display: block;
    }

    .login-box .submit span:nth-child(1) {
        top: 0;
        left: -100%;
        width: 100%;
        height: 2px;
        background: linear-gradient(90deg, transparent, #03e9f4);
        animation: btn-anim1 1s linear infinite;
    }

    @keyframes btn-anim1 {
        0% {
            left: -100%;
        }
        50%, 100% {
            left: 100%;
        }
    }

    .login-box .submit span:nth-child(2) {
        top: -100%;
        right: 0;
        width: 2px;
        height: 100%;
        background: linear-gradient(180deg, transparent, #03e9f4);
        animation: btn-anim2 1s linear infinite;
        animation-delay: .25s
    }

    @keyframes btn-anim2 {
        0% {
            top: -100%;
        }
        50%, 100% {
            top: 100%;
        }
    }

    .login-box .submit span:nth-child(3) {
        bottom: 0;
        right: -100%;
        width: 100%;
        height: 2px;
        background: linear-gradient(270deg, transparent, #03e9f4);
        animation: btn-anim3 1s linear infinite;
        animation-delay: .5s
    }

    @keyframes btn-anim3 {
        0% {
            right: -100%;
        }
        50%, 100% {
            right: 100%;
        }
    }

    .login-box .submit span:nth-child(4) {
        bottom: -100%;
        left: 0;
        width: 2px;
        height: 100%;
        background: linear-gradient(360deg, transparent, #03e9f4);
        animation: btn-anim4 1s linear infinite;
        animation-delay: .75s
    }

    @keyframes btn-anim4 {
        0% {
            bottom: -100%;
        }
        50%, 100% {
            bottom: 100%;
        }
    }
    li,span,label{
        color: white;
    }

</style>
<div class='login-page'>
    <div class="login-box">
        <h2>App Store - login </h2>
        <!-- <form> -->
            <form  action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input class="submit" type="submit" value="Log In">
            </form>
        <!-- </form> -->
    </div>
</div>


{% endblock content %}

appstor/accounts/templates/accounts/signup.html
{% extends "./layout/base.html" %}
{% load static %}

{% block content %}
<style>
    html {
        height: 100%;
    }

    body {
        margin: 0;
        padding: 0;
        font-family: sans-serif;
        background: linear-gradient(#141e30, #243b55);
    }
    form{
        display: flex;
        flex-direction: column;
    }
    .login-box {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 400px;
        padding: 40px;
        transform: translate(-50%, -50%);
        background: rgba(0, 0, 0, .5);
        box-sizing: border-box;
        box-shadow: 0 15px 25px rgba(0, 0, 0, .6);
        border-radius: 10px;
    }

    .login-box h2 {
        margin: 0 0 30px;
        padding: 0;
        color: #fff;
        text-align: center;
    }

    .login-box form {
        position: relative;
    }

    .login-box form input {
        width: 100%;
        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        margin-bottom: 30px;
        border: none;
        border-bottom: 1px solid #fff;
        outline: none;
        background:   inherit;;
    }

    .login-box form label {

        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        pointer-events: none;
        transition: .5s;
    }



    .login-box form .submit {
        position: relative;
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 16px;
        text-decoration: none;
        text-transform: uppercase;
        overflow: hidden;
        transition: .5s;
        margin-top: 40px;
        letter-spacing: 4px
    }

    .login-box .submit:hover {
        background: #03e9f4;
        color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 5px #03e9f4,
        0 0 25px #03e9f4,
        0 0 50px #03e9f4,
        0 0 100px #03e9f4;
    }

    .login-box .submit span {
        position: absolute;
        display: block;
    }

    .login-box .submit span:nth-child(1) {
        top: 0;
        left: -100%;
        width: 100%;
        height: 2px;
        background: linear-gradient(90deg, transparent, #03e9f4);
        animation: btn-anim1 1s linear infinite;
    }

    @keyframes btn-anim1 {
        0% {
            left: -100%;
        }
        50%, 100% {
            left: 100%;
        }
    }

    .login-box .submit span:nth-child(2) {
        top: -100%;
        right: 0;
        width: 2px;
        height: 100%;
        background: linear-gradient(180deg, transparent, #03e9f4);
        animation: btn-anim2 1s linear infinite;
        animation-delay: .25s
    }

    @keyframes btn-anim2 {
        0% {
            top: -100%;
        }
        50%, 100% {
            top: 100%;
        }
    }

    .login-box .submit span:nth-child(3) {
        bottom: 0;
        right: -100%;
        width: 100%;
        height: 2px;
        background: linear-gradient(270deg, transparent, #03e9f4);
        animation: btn-anim3 1s linear infinite;
        animation-delay: .5s
    }

    @keyframes btn-anim3 {
        0% {
            right: -100%;
        }
        50%, 100% {
            right: 100%;
        }
    }

    .login-box .submit span:nth-child(4) {
        bottom: -100%;
        left: 0;
        width: 2px;
        height: 100%;
        background: linear-gradient(360deg, transparent, #03e9f4);
        animation: btn-anim4 1s linear infinite;
        animation-delay: .75s
    }

    @keyframes btn-anim4 {
        0% {
            bottom: -100%;
        }
        50%, 100% {
            bottom: 100%;
        }
    }
    li,span,label{
        color: white;
    }

</style>
<div class='login-page'>
    <div class="login-box">
        <h2>App Store - Register</h2>
        <!-- <form> -->
            <form action="/signup/" method="post">
                {% csrf_token %}
                {{ form }}
                <input class="submit" type="submit" value="Signup">
            </form>
        <!-- </form> -->
    </div>
</div>

{% endblock content %}

appstor/apps/templates/apps/app_detail.html
{% extends 'apps/base.html' %}
{% load ratings %}
{% load crispy_forms_tags %}
{% load static %}

{% block main %}
    <!-- Page Content -->
    <div class='detail-page'>
        <div class="container">
            <!-- Jumbotron Header -->
            <div class='my-header'>

                    <img class="card-img-top" src="{{ app.thumbnail.url }}" alt="{{ app.title }}">

                <div style="width: 100%" class='text'>
                    <div class='title'>
                        <h2>{{ app.title }}</h2>
                        <a class="btn btn-primary" style="text-decoration:none;box-shadow: 0 15px 50px 0 rgba(0, 0, 0, 0.06);display: flex;align-items: center;border: gray solid 1px ; padding:12px;border-radius: 5px;border: none"
                           href="#">
                            <h5 style="font-size:17px;margin: 2px 8px 0 0;text-decoration: none">
                                {% if app.price == 0 %}{{ 'Free' }} {% else %} ${{ app.price }} {% endif %}</h5>
                            <img src="../../static/apps/iamges/downlaod-icon.png" alt="download"/>
                        </a>
                    </div>
                    <hr>
                    <div>{% ratings app %}</div>
                    <p class="card-text">{{ app.description|linebreaks }}</p>
                </div>


            </div>
            <div style="margin: 40px 0">
                <form method="POST">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <input class="btn btn-primary" type="submit" value="submit">
                </form>
            </div>
            {% for comment in app.comments.all %}
                <div class='commend-cart'>
                    <div class='profile'>
                        <img src="../../static/apps/iamges/profile-pic.png" alt="profile"/>
                        <div class='detail'>
                            <p>{{ comment.user.username }}</p>
                            <p>{{ comment.created }}</p>
                        </div>
                    </div>
                    <p class='text card-text'>{{ comment.content }}</p>
                </div>
            {% endfor %}
            <!-- /.row -->


        </div>
    </div>
    <!-- /.container -->
{% endblock %}

appstor/apps/templates/apps/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>appstor{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'apps/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'apps/css/heroic-features.css' %}" rel="stylesheet">
   <link rel="stylesheet" href="../../static/apps/css/baseDetail.css">

  <!--rating-->
  <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
  <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</head>

<body style="position: relative" >

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div style="max-width: none" class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% category_navbar %}
    </div>
  </nav>

  {% block main %}
  {% endblock %}
  <!-- Footer -->
  <footer style="
    width: 100%;" class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'apps/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'apps/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

appstor/apps/templates/apps/category.html
{% extends 'apps/base.html' %}

{% load static %}

{% block main %}
<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
   <header style="border: solid rgba(0,0,0,0.1) 1px;border-radius:15px;padding: 0;  box-shadow: 0 15px 50px 0 rgba(0, 0, 0, 0.06);" class="jumbotron my-4">
    <img style="border-radius:15px;width: 100%;" src="../../static/apps/iamges/header.jpg" alt="header"/>
  </header>

  <!-- Page Features -->
  <div class="row text-center">
    {% for app in category.apps.all %}
    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card h-100">
        <img class="card-img-top" src="{{app.thumbnail.url}}" alt="{{app.title}}">
        <div class="card-body">
          <h4 class="card-title"><a href = "{% url 'apps:app_detail' app.slug %}">{{app.title}}</a></h4>
          <p class="card-text">{{app.description|truncatewords:30|linebreaks}}</p>
        </div>
        <div>
          {% for cat in app.category.all %}
          <a href="#">#{{cat.title}}</a>
          {% endfor %}
        </div>
        <div class="card-footer">
          <a href="{% url 'apps:app_detail' app.slug %}" class="btn btn-primary">more detail</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}

appstor/apps/templates/apps/detail.html
<app>
    <img src="{{app.thumbnail.url}}" alt="{{app.title}}" width="200" height="100">
    <h1>{{app.title}}</h1>
    <h5>last update: {{app.updated}}</h5>
    <h5>rate: {{app.Rate}}</h5>
    <h5>status: {{app.status}}</h5>
    <p>{{app.description}}</p>
</app>

appstor/apps/templates/apps/home.html
{% for app in apps %}
<app>
    <img src="{{app.thumbnail.url}}" alt="{{app.title}}" width="200" height="100">
    <h1><a href = "{% url 'apps:app_detail' app.slug %}">{{app.title}}</a></h1>
    <h5>last update: {{app.updated}}</h5>
    <h5>rate: {{app.Rate}}</h5>
    <h5>status: {{app.status}}</h5>
    <p>{{app.description}}</p>
</app>

{% endfor %}

appstor/apps/templates/apps/index.html
{% extends 'apps/base.html' %}

{% load static %}

{% block main %}
<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
  <br/>

  <header style="border: solid rgba(0,0,0,0.1) 1px;border-radius:15px;padding: 0;  box-shadow: 0 15px 50px 0 rgba(0, 0, 0, 0.06);" class="jumbotron my-4">
    <img style="border-radius:15px;width: 100%;" src="../../static/apps/iamges/header.jpg" alt="header"/>
  </header>

  <!-- Page Features -->
  <div class="row text-center">
    {% for app in apps %}
    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card h-100">
        <img style="width: 100%;min-height: 200px;max-height: 200px;object-fit: cover" class="card-img-top" src="{{app.thumbnail.url}}" alt="{{app.title}}">
        <div class="card-body">
          <h4 class="card-title"><a href = "{% url 'apps:app_detail' app.slug %}">{{app.title}}</a></h4>
          <p class="card-text">{{app.description|truncatewords:30|linebreaks}}</p>
        </div>
        <div>
          {% for cat in app.category.all %}
          <a href="{% url 'apps:category' cat.slug %}">#{{cat.title}}</a>
          {% endfor %}
        </div>
        <div class="card-footer">
          <a href="{% url 'apps:app_detail' app.slug %}" class="btn btn-primary">more detail</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}

appstor/apps/templates/apps/partials/category_nvabar.html
<style>
     ::placeholder{
        color: #c7c7c7;
    }
    li{
        z-index: 100;
    }
     @media screen and (max-width: 1188px) and (min-width: 992px){
      form{
          margin-left: 180px;
      }
    }
     @media screen  and (max-width: 375px){
      form{
          margin-left: 40px;
      }
    }
</style>

<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul style="width: 100%" class="navbar-nav ml-auto">


        <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:home' %}">Home
                <span class="sr-only">(current)</span>
            </a>
        </li>
        {% for cat in categories %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'apps:category' cat.slug %}">{{ cat.title }}</a>
            </li>
        {% endfor %}
        <div style="top:6px;position: absolute;width: 100%;display: flex;align-items: center;justify-content: center;margin-top: 5px">
            <form style="display: flex;" action="{% url 'search:searchposts' %}" method="GET"
                  value="{{ request.GET.q }}">
                <div style="display: flex;background-color: rgba(225,225,225,0.15);border-radius: 10px;padding: 1px 5px;margin-top: 2px">
                    <input  style="color:white;background-color: rgba(0,0,0,0);border: none;outline: none;)"
                           type="text" name="q" value="{{ request.GET.q }}" placeholder="Search..."/>
                    <div style="position: relative;margin-left: 6px;min-width: 25px;">
                        <input  style="z-index:1000;padding: 0;border: none;position: absolute;
                    left: 0;
                    min-width: 25px;
                    opacity: 0;
max-width: 25px;overflow: hidden" type="submit" name="submit" value="Search"/>
                        <img style="margin-top:4px;max-width: 18px;
                    max-height: 18px;
                position: absolute;
                left: 0;
                   " src="../../../static/apps/iamges/magnifier.png"/>
                    </div>

                </div>
            </form>
        </div>
        <span style="flex: 1"></span>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
        </li>
    </ul>
</div>

appstor/apps/templates/apps/search.html
<h1>Search Page</h1>

<br/>



{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for app in results %}
<div class="col-lg-3 col-md-6 mb-4">
    <div class="card h-100">
      <img style="width: 100%;min-height: 200px;max-height: 200px;object-fit: cover" class="card-img-top" src="{{app.thumbnail.url}}" alt="{{app.title}}">
      <div class="card-body">
        <h4 class="card-title"><a href = "{% url 'apps:app_detail' app.slug %}">{{app.title}}</a></h4>
        <p class="card-text">{{app.description|truncatewords:30|linebreaks}}</p>
      </div>
      <div>
        {% for cat in app.category.all %}
        <a href="{% url 'apps:category' cat.slug %}">#{{cat.title}}</a>
        {% endfor %}
      </div>
      <div class="card-footer">
        <a href="{% url 'apps:app_detail' app.slug %}" class="btn btn-primary">more detail</a>
      </div>
    </div>
  </div>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

appstor/apps/templates/apps/search_app.html
{% extends 'apps/base.html' %}

{% load static %}

{% block main %}
<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
  <br/>
  <header style="border: solid rgba(0,0,0,0.1) 1px;border-radius:15px;padding: 0;  box-shadow: 0 15px 50px 0 rgba(0, 0, 0, 0.06);" class="jumbotron my-4">
    <img style="border-radius:15px;width: 100%;" src="../../static/apps/iamges/header.jpg" alt="header"/>
  </header>

  {% if submitbutton == 'Search' and request.GET.q != '' %}
  {% if results %}
  <h1>Results for <b>{{ request.GET.q }}</b></h1>
  <br/><br/>
  
  <!-- Page Features -->
  <div class="row text-center">
    {% for app in results %}
    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card h-100">
        <img style="width: 100%;min-height: 200px;max-height: 200px;object-fit: cover" class="card-img-top" src="{{app.thumbnail.url}}" alt="{{app.title}}">
        <div class="card-body">
          <h4 class="card-title"><a href = "{% url 'apps:app_detail' app.slug %}">{{app.title}}</a></h4>
          <p class="card-text">{{app.description|truncatewords:30|linebreaks}}</p>
        </div>
        <div>
          {% for cat in app.category.all %}
          <a href="{% url 'apps:category' cat.slug %}">#{{cat.title}}</a>
          {% endfor %}
        </div>
        <div class="card-footer">
          <a href="{% url 'apps:app_detail' app.slug %}" class="btn btn-primary">more detail</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- /.row -->

</div>
{% else %}
No search results for this query
{% endif %}
{% endif %}
<!-- /.container -->
{% endblock %}